### ISSUE TITLE
Python API: accessing uninitialised object built-ins can cause segfault

### ISSUE THREAD

**Issue by Renegade334** [hexchat/hexchat#1258]
Tested under python-2.7 and python-3.4. It appears that various built-in methods/attributes of objects that belong to classes defined in the Hexchat API don't exist until one of them is specifically referenced. This can lead to very unexpected behaviour. For example, the following will cause Hexchat to segfault:

```python
def callback_passed_to_hook_print_attrs(word, word_eol, event, attrs):
  mytype = type(attrs)
###### Program received signal SIGSEGV, Segmentation fault. ######
```

However, the following is fine:

```python
def callback_passed_to_hook_print_attrs(word, word_eol, event, attrs):
  # Arbitrarily request a built-in object attribute
  attrs.__class__

  # Now this will work fine
  mytype = type(attrs)
```

As is this, even though the built-in attribute requested is nothing to do with the `type()` call:

```python
def callback_passed_to_hook_print_attrs(word, word_eol, event, attrs):
  attrs.__str__

  # This now works as well
  mytype = type(attrs)
```

Running `dir()` before and after yields the following:

```python
def callback_passed_to_hook_print_attrs(word, word_eol, event, attrs):
  try:
    hexchat.prnt(str(dir(attrs)))
  except TypeError as err:
    hexchat.prnt(str(err))
# object does not provide __dir__

  attrs.__class__

  try:
    hexchat.prnt(str(dir(attrs)))
  except TypeError as err:
    hexchat.prnt(str(err))
# ['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'time']
```

Once an object class has been "initialised" like this, any future objects of the same class will **not** have the same problem (ie. will have their built-in attributes correctly populated), even if the script itself is reloaded, but reloading the Python plugin restores the bug. As such, I suspect that either the type object or the method def is not being initalised correctly in `plugins/python.c`. I have no experience with the Python C-API, so I can't offer anything more than a stab in the dark.

Below is an example backtrace.

```
Program received signal SIGSEGV, Segmentation fault.
PyObject_Str (v=0x7fffe46d7aa0 <Attribute_Type>) at ../Objects/object.c:505
505	../Objects/object.c: No such file or directory.
(gdb) bt
#0  PyObject_Str (v=0x7fffe46d7aa0 <Attribute_Type>) at ../Objects/object.c:505
#1  0x00007fffd2aae3a5 in unicode_new.29110 (
    type=0x7fffd2ebb800 <PyUnicode_Type>, args=<optimised out>, 
    kwds=<optimised out>) at ../Objects/unicodeobject.c:14756
#2  0x00007fffd2a77f13 in type_call.25596 (
    type=0x7fffd2ebb800 <PyUnicode_Type>, args=0x7fffd0eb21d0, kwds=0x0)
    at ../Objects/typeobject.c:854
#3  0x00007fffd29ea458 in PyObject_Call (
    func=func@entry=0x7fffd2ebb800 <PyUnicode_Type>, 
    arg=arg@entry=0x7fffd0eb21d0, kw=kw@entry=0x0)
    at ../Objects/abstract.c:2067
#4  0x00007fffd29aade9 in do_call (nk=<optimised out>, na=<optimised out>, 
    pp_stack=0x7fffffffb780, func=<optimised out>) at ../Python/ceval.c:4456
#5  call_function (oparg=<optimised out>, pp_stack=0x7fffffffb780)
    at ../Python/ceval.c:4254
#6  PyEval_EvalFrameEx (f=f@entry=0x1f51238, throwflag=throwflag@entry=0)
    at ../Python/ceval.c:2829
#7  0x00007fffd2ad5516 in PyEval_EvalCodeEx (_co=0x7fffd0eab1e0, 
    globals=<optimised out>, locals=locals@entry=0x0, 
    args=args@entry=0x7fffd0ec35b0, argcount=4, kws=kws@entry=0x0, 
    kwcount=kwcount@entry=0, defs=defs@entry=0x7fffd0f3b920, 
    defcount=defcount@entry=1, kwdefs=0x0, closure=0x0)
    at ../Python/ceval.c:3578
#8  0x00007fffd2ad5b46 in function_call.15149 (func=0x7fffd0f1fbf8, 
    arg=0x7fffd0ec3598, kw=0x0) at ../Objects/funcobject.c:632
#9  0x00007fffd29ea458 in PyObject_Call (func=func@entry=0x7fffd0f1fbf8, 
    arg=arg@entry=0x7fffd0ec3598, kw=kw@entry=0x0)
    at ../Objects/abstract.c:2067
#10 0x00007fffd29fac0b in call_function_tail (args=0x7fffd0ec3598, 
    callable=0x7fffd0f1fbf8) at ../Objects/abstract.c:2105
#11 PyObject_CallFunction (callable=0x7fffd0f1fbf8, 
    format=format@entry=0x7fffe44d522d "(OOOO)") at ../Objects/abstract.c:2131
#12 0x00007fffe44d1db1 in Callback_Print_Attrs (word=<optimised out>, 
    attrs=<optimised out>, userdata=0x1c5b510) at python.c:688
#13 0x000000000046de02 in plugin_hook_run (sess=sess@entry=0x16da000, 
    name=0x493ace "Your Message", word=word@entry=0x7fffffffbb60, 
    word_eol=word_eol@entry=0x0, attrs=attrs@entry=0x7fffffffbb30, 
    type=type@entry=24) at plugin.c:557
#14 0x000000000047064e in plugin_emit_print (sess=sess@entry=0x16da000, 
    word=word@entry=0x7fffffffbb60, server_time=server_time@entry=0)
    at plugin.c:644
#15 0x0000000000477545 in text_emit (index=index@entry=149, 
    sess=sess@entry=0x16da000, a=<optimised out>, a@entry=0x8b3ec6 "TestUser", 
    b=b@entry=0x2013010 "fo", c=c@entry=0x7fffffffbd10 "@", d=d@entry=0x0, 
    timestamp=0) at text.c:2078
#16 0x00000000004609c8 in inbound_chanmsg (serv=0x8b3c00,
    sess=sess@entry=0x16da000, chan=chan@entry=0x16da020 "#", 
    from=0x8b3ec6 "TestUser", text=text@entry=0x2013010 "fo", 
    fromme=<optimised out>, fromme@entry=1 '\001', id=<optimised out>, 
    id@entry=0, tags_data=tags_data@entry=0x7fffffffbdd0) at inbound.c:472
#17 0x000000000046ca8d in handle_say (sess=sess@entry=0x16da000, 
    text=0x2013010 "fo", text@entry=0x1e8b970 "fo", 
    check_spch=check_spch@entry=1) at outbound.c:4553
#18 0x000000000046d94b in handle_user_input (nocommand=0, history=1, 
    text=0x1e8b970 "fo", sess=0x16da000) at outbound.c:4786
#19 handle_multiline (sess=0x16da000, cmd=0x1e8b970 "fo", history=1, 
    nocommand=0) at outbound.c:4841
#20 0x0000000000435afc in mg_inputbox_cb (igad=0x8465e0, 
    gui=0x6be580 <static_mg_gui>) at maingui.c:341
...
```

**Comment by RenaKunisaki** [comment]
I think I've run into the same bug: just start Hexchat and type:

    /py exec print(type(hexchat.get_context()))
and boom, segfault. I'm using v2.10.2 on Arch AMD64.

Interestingly, this does *not* crash:

    /py exec print(hexchat.get_context())
That outputs ContextObject as expected, but afterward, the previous line still crashes.
