### ISSUE TITLE
Segfault on right-clicking status bar icon

### ISSUE THREAD

**Issue by f2404** [hexchat/hexchat#1818]
Arch Linux, hexchat 2.12.1 segfaulted on right-clicking status bar icon. Not sure how to reproduce the crash - it's working fine after restart.
```
kernel: hexchat[966]: segfault at f ip 000055894506e924 sp 00007ffead42b1f0 error 4  in hexchat[55894501d000+cd000]
systemd[1]: Started Process Core Dump (PID 15241/UID 0).
systemd-coredump[15242]: Process 966 (hexchat) of user 1000 dumped core.

Stack trace of thread 966:
#0  0x000055894506e924 n/a (hexchat)
#1  0x00007f64b32f3f85 g_closure_invoke (libgobject-2.0.so.0)
#2  0x00007f64b3305f92 n/a (libgobject-2.0.so.0)
#3  0x00007f64b330ebfc g_signal_emit_valist (libgobject-2.0.so.0)
#4  0x00007f64b330efdf g_signal_emit (libgobject-2.0.so.0)
#5  0x00007f64b50c9189 n/a (libgtk-x11-2.0.so.0)
#6  0x00007f64b50547ac n/a (libgtk-x11-2.0.so.0)
#7  0x00007f64b32f3f85 g_closure_invoke (libgobject-2.0.so.0)
#8  0x00007f64b3305f92 n/a (libgobject-2.0.so.0)
#9  0x00007f64b330e69f g_signal_emit_valist (libgobject-2.0.so.0)
#10 0x00007f64b330efdf g_signal_emit (libgobject-2.0.so.0)
#11 0x00007f64b516c8cc n/a (libgtk-x11-2.0.so.0)
#12 0x00007f64b5052f74 gtk_propagate_event (libgtk-x11-2.0.so.0)
#13 0x00007f64b505332b gtk_main_do_event (libgtk-x11-2.0.so.0)
#14 0x00007f64b4cca46c n/a (libgdk-x11-2.0.so.0)
#15 0x00007f64b301ee67 g_main_context_dispatch (libglib-2.0.so.0)
#16 0x00007f64b301f0d0 n/a (libglib-2.0.so.0)
#17 0x00007f64b301f3f2 g_main_loop_run (libglib-2.0.so.0)
#18 0x00007f64b50523a7 gtk_main (libgtk-x11-2.0.so.0)
#19 0x0000558945057949 fe_main (hexchat)
#20 0x000055894504bc58 main (hexchat)
#21 0x00007f64b2828291 __libc_start_main (libc.so.6)
#22 0x000055894504bd89 _start (hexchat)
```

**Comment by f2404** [comment]
Ok, it happened again. Maybe it crashes after receiving a message in a channel.

**Comment by f2404** [comment]
Does not seem to be crashing when compiled after `./autogen.sh ... --enable-debug`.

**Comment by f2404** [comment]
Seems to be not reproducible on 2.12.2.

**Comment by TingPing** [comment]
For what its worth nothing directly related to that changed.

**Comment by f2404** [comment]
Yeah, it could be that some other packages in my system have been updated during those 20 days.
Anyway, hexchat is not crashing anymore; and 20 days ago, I was able to crash it with 100% result.

**Comment by f2404** [comment]
In fact, it's also happening on version 2.12.2.
How to reproduce: set auto-connect to channels on start (2 channels for me); right-click the icon before connecting to the channels - the menu is shown; wait for connection and right-click again - segfault.

**Comment by bebehei** [comment]
I'm able to do some similar things. I'm not sure, how related this is. I can do it, when right clicking the trayicon twice. (Opening the context menu, then closing it and opening it again.)

**Comment by aravindhp** [comment]
I am seeing this issue too with hexchat-2.14.1 on Fedora 27. 
```
{   "signal": 11
,   "executable": "/usr/bin/hexchat"
,   "stacktrace":
      [ {   "crash_thread": true
        ,   "frames":
              [ {   "address": 94597573884996
                ,   "build_id": "f98d1242dde141a633f84a06f1c05fbd807ad49c"
                ,   "build_id_offset": 343108
                ,   "function_name": "tray_menu_cb"
                ,   "file_name": "/usr/bin/hexchat"
                }
              , {   "address": 139706112153405
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 63293
                ,   "function_name": "g_closure_invoke"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112230622
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 140510
                ,   "function_name": "signal_emit_unlocked_R"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112265477
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 175365
                ,   "function_name": "g_signal_emit_valist"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112267887
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 177775
                ,   "function_name": "g_signal_emit"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706101791113
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 1874313
                ,   "function_name": "gtk_status_icon_button_press"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 139706101257853
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 1341053
                ,   "function_name": "_gtk_marshal_BOOLEAN__BOXED"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 139706112153405
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 63293
                ,   "function_name": "g_closure_invoke"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112230622
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 140510
                ,   "function_name": "signal_emit_unlocked_R"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112263839
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 173727
                ,   "function_name": "g_signal_emit_valist"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706112267887
                ,   "build_id": "d2f6cbc61773c7e57ce6db55e92ac5435ff767c8"
                ,   "build_id_offset": 177775
                ,   "function_name": "g_signal_emit"
                ,   "file_name": "/lib64/libgobject-2.0.so.0"
                }
              , {   "address": 139706102499388
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 2582588
                ,   "function_name": "gtk_widget_event_internal"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 139706101249052
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 1332252
                ,   "function_name": "gtk_propagate_event"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 139706101250107
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 1333307
                ,   "function_name": "gtk_main_do_event"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 139706097422156
                ,   "build_id": "c3d85734a20826e8dfc1d9f00349571dfd684ed5"
                ,   "build_id_offset": 397132
                ,   "function_name": "gdk_event_dispatch"
                ,   "file_name": "/lib64/libgdk-x11-2.0.so.0"
                }
              , {   "address": 139706109168503
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 306039
                ,   "function_name": "g_main_context_dispatch"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109169440
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 306976
                ,   "function_name": "g_main_context_iterate.isra.23"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109170226
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 307762
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706101245991
                ,   "build_id": "ae49410f4507afc51e5be97c94ba3f241c061f69"
                ,   "build_id_offset": 1329191
                ,   "function_name": "gtk_main"
                ,   "file_name": "/lib64/libgtk-x11-2.0.so.0"
                }
              , {   "address": 94597573790329
                ,   "build_id": "f98d1242dde141a633f84a06f1c05fbd807ad49c"
                ,   "build_id_offset": 248441
                ,   "function_name": "fe_main"
                ,   "file_name": "/usr/bin/hexchat"
                }
              , {   "address": 94597573741673
                ,   "build_id": "f98d1242dde141a633f84a06f1c05fbd807ad49c"
                ,   "build_id_offset": 199785
                ,   "function_name": "main"
                ,   "file_name": "/usr/bin/hexchat"
                } ]
        }
      , {   "frames":
              [ {   "address": 139706067704939
                ,   "build_id": "b097b427ace57ac70bb636f7a41af7f10a69a851"
                ,   "build_id_offset": 961643
                ,   "function_name": "__poll"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 139706109169305
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 306841
                ,   "function_name": "g_main_context_iterate.isra.23"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109169580
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 307116
                ,   "function_name": "g_main_context_iteration"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109169649
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 307185
                ,   "function_name": "glib_worker_main"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109330566
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 468102
                ,   "function_name": "g_thread_proxy"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706070664459
                ,   "build_id": "6b24143b0992f85d680b1a2f451ce049124ce5d6"
                ,   "build_id_offset": 29963
                ,   "function_name": "start_thread"
                ,   "file_name": "/lib64/libpthread.so.0"
                }
              , {   "address": 139706067747183
                ,   "build_id": "b097b427ace57ac70bb636f7a41af7f10a69a851"
                ,   "build_id_offset": 1003887
                ,   "function_name": "__clone"
                ,   "file_name": "/lib64/libc.so.6"
                } ]
        }
      , {   "frames":
              [ {   "address": 139706067704939
                ,   "build_id": "b097b427ace57ac70bb636f7a41af7f10a69a851"
                ,   "build_id_offset": 961643
                ,   "function_name": "__poll"
                ,   "file_name": "/lib64/libc.so.6"
                }
              , {   "address": 139706109169305
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 306841
                ,   "function_name": "g_main_context_iterate.isra.23"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706109170226
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 307762
                ,   "function_name": "g_main_loop_run"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706115365718
                ,   "build_id": "8aaf7d0cb428b58d6e02a03bd903d6cd1e197666"
                ,   "build_id_offset": 838486
                ,   "function_name": "gdbus_shared_thread_func"
                ,   "file_name": "/lib64/libgio-2.0.so.0"
                }
              , {   "address": 139706109330566
                ,   "build_id": "c5aba5b8d3105d4118bbd5a27c2d4dbbcd0924a1"
                ,   "build_id_offset": 468102
                ,   "function_name": "g_thread_proxy"
                ,   "file_name": "/lib64/libglib-2.0.so.0"
                }
              , {   "address": 139706070664459
                ,   "build_id": "6b24143b0992f85d680b1a2f451ce049124ce5d6"
                ,   "build_id_offset": 29963
                ,   "function_name": "start_thread"
                ,   "file_name": "/lib64/libpthread.so.0"
                }
              , {   "address": 139706067747183
                ,   "build_id": "b097b427ace57ac70bb636f7a41af7f10a69a851"
                ,   "build_id_offset": 1003887
                ,   "function_name": "__clone"
                ,   "file_name": "/lib64/libc.so.6"
                } ]
        } ]
}
```
It typically happens on right clicking the hexchat icon on the Gnome top bar after I have been using it for a while. However it does not occur always. It is unclear what sequence of events make this happen. Here is a [link](https://retrace.fedoraproject.org/faf/reports/272838/) to the Fedora Analysis Framework.

**Comment by xoan** [comment]
It is always reproducible in hexchat-2.14.1 (Arch Linux) the second time you try to show the context menu by right click on tray icon.

I'm not sure this gdb output could be helpful:

```
(gdb) run
Starting program: /usr/bin/hexchat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library &quot;/usr/lib/libthread_db.so.1&quot;.
[New Thread 0x7fffe620c700 (LWP 24334)]
[New Thread 0x7fffe5a0b700 (LWP 24335)]
[New Thread 0x7fffdcb80700 (LWP 24337)]

Thread 1 &quot;hexchat&quot; received signal SIGSEGV, Segmentation fault.
0x00005555555a2b56 in ?? ()
(gdb) backtrace
#0  0x00005555555a2b56 in  ()
#1  0x00007ffff720ec2d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#2  0x00007ffff7222bb0 in  () at /usr/lib/libgobject-2.0.so.0
#3  0x00007ffff722b746 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff722c180 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff684b2f2 in  () at /usr/lib/libgtk-x11-2.0.so.0
#6  0x00007ffff67d47cc in  () at /usr/lib/libgtk-x11-2.0.so.0
#7  0x00007ffff720ec2d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7222bb0 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff722b0d1 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff722c180 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff68ef235 in  () at /usr/lib/libgtk-x11-2.0.so.0
#12 0x00007ffff67d2a0e in gtk_propagate_event ()
    at /usr/lib/libgtk-x11-2.0.so.0
#13 0x00007ffff67d2e43 in gtk_main_do_event () at /usr/lib/libgtk-x11-2.0.so.0
#14 0x00007ffff644bd5e in  () at /usr/lib/libgdk-x11-2.0.so.0
#15 0x00007ffff6f33458 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff6f336a1 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff6f339d2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff67d1df3 in gtk_main () at /usr/lib/libgtk-x11-2.0.so.0
---Type &lt;return&gt; to continue, or q &lt;return&gt; to quit---
#19 0x000055555558a08a in fe_main ()
#20 0x0000555555581184 in main ()
(gdb)
```

**Comment by xoan** [comment]
This is no longer reproducible in 2.14.2.
