### ISSUE TITLE
random crash (SIGSEGV)

### ISSUE THREAD

**Issue by pabs3** [hexchat/hexchat#1971]
I got a random crash (SIGSEGV) in Debian hexchat 2.12.4-2 on Debian stretch. If the below gdb backtrace summary and attached full gdb backtrace isn't useful, please close this bug.

```backtrace
Core was generated by `hexchat'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa1d300ab90 in g_io_channel_new_file (filename=<optimized out>, mode=<optimized out>, error=<optimized out>) at ././glib/giounix.c:571
571	././glib/giounix.c: No such file or directory.
[Current thread is 1 (Thread 0x7fa1d691aa80 (LWP 23661))]
#0  0x00007fa1d300ab90 in g_io_channel_new_file (filename=<optimized out>, mode=<optimized out>, error=<optimized out>) at ././glib/giounix.c:571
#1  0x0000000000000008 in  ()
#2  0x00007fa1d2fc4a60 in g_main_context_iterate (context=0x1, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ././glib/gmain.c:3929
#3  0x00007fa1d2fc4d82 in g_main_loop_run (loop=0x5576a9bdfcf0) at ././glib/gmain.c:4125
#4  0x00007fa1d62b83b7 in IA__gtk_main () at ./gtk/gtkmain.c:1268
#5  0x00005576a85fa6c9 in fe_main () at fe-gtk.c:347
#6  0x00005576a85ee9e8 in main (argc=<optimized out>, argv=<optimized out>) at hexchat.c:1141
```

**Comment by pabs3** [comment]
Woops, full trace attached now.

**Comment by pabs3** [comment]
Woops, forgot attaching only works with JavaScript on.

Attached the [full crash dump](https://github.com/hexchat/hexchat/files/835783/hexchat-2.12.4-2-crash.txt).

**Comment by TingPing** [comment]
Can you reproduce? Can you install debug symbols? Otherwise that probably isn't very useful not.

**Comment by pabs3** [comment]
It was a random crash, I have no idea what caused it and have no way to reproduce it.

The backtrace I provided was with debug symbols installed so it should be useful.

If it isn't useful, please just close this.
