### ISSUE TITLE
AutoLoad failed for: .\plugins\hcpython3.dll

### ISSUE THREAD

**Issue by CanadianJeff** [hexchat/hexchat#2530]
```
U:\programs\windows\HexChat>dir /w plugins
 Volume in drive U is share
 Volume Serial Number is B007-3C3D

 Directory of U:\programs\windows\HexChat\plugins

[.]                         [..]                        hclua.dll
hcnotifications-winrt.dll   hcpython3.dll
               3 File(s)        127,488 bytes
               2 Dir(s)  355,654,787,072 bytes free

U:\programs\windows\HexChat>
```

**Comment by drproteus** [comment]
Apologies for the necro, but I'm hitting this for the first time with the scoop installer (https://github.com/ScoopInstaller/Extras/blob/master/bucket/hexchat.json) on a fresh Windows install which doesn't make much sense since the file (as in OP's case) _is_ present. 

```
PS C:\Users\jgori\scoop\apps\hexchat\current\plugins> dir


    Directory: C:\Users\jgori\scoop\apps\hexchat\current\plugins


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/12/2022   6:38 PM          14336 hcchecksum.dll
-a----         2/12/2022   6:38 PM          13312 hcexec.dll
-a----         2/12/2022   6:38 PM          31232 hcfishlim.dll
-a----         2/12/2022   6:37 PM          36352 hclua.dll
-a----         2/12/2022   6:38 PM          42496 hcnotifications-winrt.dll
-a----         2/12/2022   6:38 PM          87552 hcperl.dll
-a----         2/12/2022   6:38 PM          67584 hcpython2.dll
-a----         2/12/2022   6:38 PM          67584 hcpython3.dll
-a----         2/12/2022   6:38 PM          18432 hcsysinfo.dll
-a----         2/12/2022   6:38 PM          11264 hcupd.dll
-a----         2/12/2022   6:38 PM          12800 hcwinamp.dll
```

Version: 2.16.1
OS: Windows 10

Startup goes like this:
```
 Checksum plugin loaded
 Exec plugin loaded
 FiSHLiM plugin loaded
 Lua version 1.3/5.1 loaded.
 Perl interface loaded
 Python interface loaded
 From cffi callback <function _on_plugin_init at 0x0000020CAE2AE4A8>:
 Traceback (most recent call last):
   File "<init code for '_hexchat_embedded'>", line 528, in _on_plugin_init
   File "<init code for '_hexchat_embedded'>", line 367, in autoload
 NameError: global name 'FileNotFoundError' is not defined
 AutoLoad failed for: .\plugins\hcpython3.dll
 '.\plugins\hcpython3.dll': The specified module could not be found.
 Update Checker plugin loaded
 Winamp plugin loaded
 Sysinfo plugin loaded
```

**Comment by TingPing** [comment]
@drproteus And if you use the regular installer?

**Comment by drproteus** [comment]
@TingPing Without checking the Python integration in the setup wizard (which is presumably implicitly enabled in the scoop method), it does connect fine without error, but of course it's not trying to use Python. With that option checked, it tries to install Python 3.6 at the end of the install, but I've already got Python 3.11 configured (also through scoop-- though it is failing with that) so I backed out of that installer. I overwrote that with Python 3.6 (again, via scoop but fully present in the path). I did not however run `~\scoop\apps\python36\current\install-pep-514.reg` as suggested, which may be required. But in this case I didn't even get an error, just exits immediately after trying to connect to a server. 

I'm aware that this is full of odd inconsistencies and I really out to be attempting this in a clean-room environment (obviously trying with the installer at the end of HexChat's setup), and the onus is likely more on however scoop is invoking [HexChat 2.16.1 x64.exe](https://dl.hexchat.net/hexchat/HexChat%202.16.1%20x64.exe), but is there a switch somewhere that allows one to specify the python path for HexChat specifically? If it requires a very specific version of Python 3, that's cool, I just don't want to mess with the "system" Python (as if there is such a thing on Windows). 

Anyway, it does seem to be an odd Windows+Scoop+Python edge-case and not an outright HexChat issue, so no worries. Thank you!

**Comment by TingPing** [comment]
> With that option checked, it tries to install Python 3.6 at the end of the install, but I've already got Python 3.11 configured

Well that doesn't matter. You need 3.6. It's what its built against.
